services:
  multivol-backend:
    restart: always
    build:
      dockerfile: Dockerfile-backend
    env_file: .env
    volumes:
      - ./shared_volume:/shared_volume

  multivol-frontend:
    restart: always
    volumes:
      - ./shared_volume:/shared_volume
    build:
      dockerfile: Dockerfile-frontend
    ports:
      - "8501:8501"
